# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'

Description: Creates team development IAM permissions boundary policy

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: System Classification
      Parameters:
      - pOrg
      - pSystem
    - Label:
        default: IAM Policy Name Qualifier
      Parameters:
      - pPolicyNameQualifier

    ParameterLabels:
      pOrg:
        default: Business Scope
      pSystem:
        default: System Identifier
      pPolicyNameQualifier:
        default: IAM policy name qualifier

Parameters:
  pOrg:
    Type: String
    Description: Used to qualify IAM policy resource name
    Default: acme

  pSystem:
    Type: String
    Description: Used to qualify IAM policy resource name
    Default: base

  pPolicyNameQualifier:
    Type: String
    Description: Used to qualify IAM policy resource name
    Default: team-dev-boundary

Resources:
  rManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${pOrg}-${pSystem}-${pPolicyNameQualifier}'
      PolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "AllowAllWithExceptions",
              "Effect": "Allow",
              "NotAction": [
                "iam:*",
                "organizations:*",
                "account:*"
              ],
              "Resource": "*"
            },
            {
              "Sid": "AllowIamReadOnly",
              "Effect": "Allow",
              "Action": [
                "iam:Get*",
                "iam:List*"
              ],
              "Resource": "*"
            },
            {
              "Sid": "DenyWriteAccessStackSets",
              "Effect": "Deny",
              "Action": [
                "cloudformation:DeleteStack",
                "cloudformation:UpdateStack"
              ],
              "Resource": "arn:aws:cloudformation::*:stack/StackSet-*"
            },
            {
              "Sid": "DenyVPCWrite",
              "Effect": "Deny",
              "Action": [
                "ec2:CreateCustomerGateway",
                "ec2:CreateDefaultSubnet",
                "ec2:CreateDefaultVpc",
                "ec2:CreateDhcpOptions",
                "ec2:CreateEgressOnlyInternetGateway",
                "ec2:CreateFlowLogs",
                "ec2:CreateInternetGateway",
                "ec2:CreateNatGateway",
                "ec2:CreateNetworkAcl",
                "ec2:CreateNetworkAclEntry",
                "ec2:CreateRoute",
                "ec2:CreateRouteTable",
                "ec2:CreateSubnet",
                "ec2:CreateVpc",
                "ec2:CreateVpcEndpoint",
                "ec2:CreateVpcEndpointConnectionNotification",
                "ec2:CreateVpcEndpointServiceConfiguration",
                "ec2:CreateVpnConnection",
                "ec2:CreateVpnConnectionRoute",
                "ec2:CreateVpnGateway",
                "ec2:EnableVgwRoutePropagation",
                "ec2:EnableVpcClassicLinkDnsSupport",
                "ec2:MoveAddressToVpc",
                "ec2:RejectVpcEndpointConnections",
                "ec2:RestoreAddressToClassic",
                "ec2:AcceptVpcPeeringConnection",
                "ec2:AttachClassicLinkVpc",
                "ec2:CreateVpcPeeringConnection",
                "ec2:EnableVpcClassicLink",
                "ec2:RejectVpcPeeringConnection",
                "directconnect:*"
              ],
              "Resource": "*"
            }
         ]
      }

Outputs:
  oPermissionsBoundaryArn:
    Description: Dev Team IAM Permissions Boundary Policy ARN
    Value: !Ref rManagedPolicy
    Export:
      Name: !Sub '${pOrg}-${pSystem}-${pPolicyNameQualifier}::arn'